version: "3"
services:
  python-scraper:
    container_name: python-scraper
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./:/python-scraper
